from PyQt5 import QtCore, QtGui, QtWidgets
from bankir import bankir
from PyQt5.QtWidgets import *
from PyQt5 import QtGui, QtSvg
import json
import GraphDrawer
import time
from PyQt5.QtCore import QTimer, QEventLoop

processes = 4
resources = 4
max_resources = [1, 1, 1, 1]
label = 'Безопасная последовательность:'
sequence = ""
with open("config.json") as f:
    config = json.load(f)


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1000, 700)
        mainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        mainWindow.setStyleSheet("background-color: rgb(216, 218, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.svgWidget = QtSvg.QSvgWidget()
        self.svgWidget.setGeometry(50, 50, 350, 350)

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(740, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(600, 340, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(20, 440, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(20, 480, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(60, 360, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.startButton.setObjectName("startButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(400, 20, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(200, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(20, 280, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(260, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 180, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 230, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(80, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(140, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(60, 110, 238, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget_2.sizePolicy().hasHeightForWidth())
        self.layoutWidget_2.setSizePolicy(sizePolicy)
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.allButton_03 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_03.sizePolicy().hasHeightForWidth())
        self.allButton_03.setSizePolicy(sizePolicy)
        self.allButton_03.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_03.setObjectName("allButton_03")
        self.gridLayout_3.addWidget(self.allButton_03, 0, 0, 1, 1)
        self.allButton_02 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_02.sizePolicy().hasHeightForWidth())
        self.allButton_02.setSizePolicy(sizePolicy)
        self.allButton_02.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_02.setObjectName("allButton_02")
        self.gridLayout_3.addWidget(self.allButton_02, 0, 1, 1, 1)
        self.allButton_01 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_01.sizePolicy().hasHeightForWidth())
        self.allButton_01.setSizePolicy(sizePolicy)
        self.allButton_01.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_01.setObjectName("allButton_01")
        self.gridLayout_3.addWidget(self.allButton_01, 0, 2, 1, 1)
        self.allButton_00 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_00.sizePolicy().hasHeightForWidth())
        self.allButton_00.setSizePolicy(sizePolicy)
        self.allButton_00.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_00.setObjectName("allButton_00")
        self.gridLayout_3.addWidget(self.allButton_00, 0, 3, 1, 1)
        self.allButton_13 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_13.sizePolicy().hasHeightForWidth())
        self.allButton_13.setSizePolicy(sizePolicy)
        self.allButton_13.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_13.setObjectName("allButton_13")
        self.gridLayout_3.addWidget(self.allButton_13, 1, 0, 1, 1)
        self.allButton_12 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_12.sizePolicy().hasHeightForWidth())
        self.allButton_12.setSizePolicy(sizePolicy)
        self.allButton_12.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_12.setObjectName("allButton_12")
        self.gridLayout_3.addWidget(self.allButton_12, 1, 1, 1, 1)
        self.allButton_11 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_11.sizePolicy().hasHeightForWidth())
        self.allButton_11.setSizePolicy(sizePolicy)
        self.allButton_11.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_11.setObjectName("allButton_11")
        self.gridLayout_3.addWidget(self.allButton_11, 1, 2, 1, 1)
        self.allButton_10 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_10.sizePolicy().hasHeightForWidth())
        self.allButton_10.setSizePolicy(sizePolicy)
        self.allButton_10.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_10.setObjectName("allButton_10")
        self.gridLayout_3.addWidget(self.allButton_10, 1, 3, 1, 1)
        self.allButton_23 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_23.sizePolicy().hasHeightForWidth())
        self.allButton_23.setSizePolicy(sizePolicy)
        self.allButton_23.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_23.setObjectName("Button_23")
        self.gridLayout_3.addWidget(self.allButton_23, 2, 0, 1, 1)
        self.allButton_22 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_22.sizePolicy().hasHeightForWidth())
        self.allButton_22.setSizePolicy(sizePolicy)
        self.allButton_22.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_22.setObjectName("allButton_22")
        self.gridLayout_3.addWidget(self.allButton_22, 2, 1, 1, 1)
        self.allButton_21 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_21.sizePolicy().hasHeightForWidth())
        self.allButton_21.setSizePolicy(sizePolicy)
        self.allButton_21.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_21.setObjectName("allButton_21")
        self.gridLayout_3.addWidget(self.allButton_21, 2, 2, 1, 1)
        self.allButton_20 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_20.sizePolicy().hasHeightForWidth())
        self.allButton_20.setSizePolicy(sizePolicy)
        self.allButton_20.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_20.setObjectName("allButton_20")
        self.gridLayout_3.addWidget(self.allButton_20, 2, 3, 1, 1)
        self.allButton_33 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_33.sizePolicy().hasHeightForWidth())
        self.allButton_33.setSizePolicy(sizePolicy)
        self.allButton_33.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_33.setObjectName("allButton_33")
        self.gridLayout_3.addWidget(self.allButton_33, 3, 0, 1, 1)
        self.allButton_32 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_32.sizePolicy().hasHeightForWidth())
        self.allButton_32.setSizePolicy(sizePolicy)
        self.allButton_32.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_32.setObjectName("Button_32")
        self.gridLayout_3.addWidget(self.allButton_32, 3, 1, 1, 1)
        self.allButton_31 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_31.sizePolicy().hasHeightForWidth())
        self.allButton_31.setSizePolicy(sizePolicy)
        self.allButton_31.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_31.setObjectName("Button_31")
        self.gridLayout_3.addWidget(self.allButton_31, 3, 2, 1, 1)
        self.allButton_30 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.allButton_30.sizePolicy().hasHeightForWidth())
        self.allButton_30.setSizePolicy(sizePolicy)
        self.allButton_30.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.allButton_30.setObjectName("allButton_30")
        self.gridLayout_3.addWidget(self.allButton_30, 3, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(20, 130, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(600, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(400, 110, 238, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget_3.sizePolicy().hasHeightForWidth())
        self.layoutWidget_3.setSizePolicy(sizePolicy)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.maxButton_03 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_03.sizePolicy().hasHeightForWidth())
        self.maxButton_03.setSizePolicy(sizePolicy)
        self.maxButton_03.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_03.setObjectName("maxButton_03")
        self.gridLayout_4.addWidget(self.maxButton_03, 0, 0, 1, 1)
        self.maxButton_02 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_02.sizePolicy().hasHeightForWidth())
        self.maxButton_02.setSizePolicy(sizePolicy)
        self.maxButton_02.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_02.setObjectName("maxButton_02")
        self.gridLayout_4.addWidget(self.maxButton_02, 0, 1, 1, 1)
        self.maxButton_01 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_01.sizePolicy().hasHeightForWidth())
        self.maxButton_01.setSizePolicy(sizePolicy)
        self.maxButton_01.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_01.setObjectName("maxButton_01")
        self.gridLayout_4.addWidget(self.maxButton_01, 0, 2, 1, 1)
        self.maxButton_00 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_00.sizePolicy().hasHeightForWidth())
        self.maxButton_00.setSizePolicy(sizePolicy)
        self.maxButton_00.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_00.setObjectName("maxButton_00")
        self.gridLayout_4.addWidget(self.maxButton_00, 0, 3, 1, 1)
        self.maxButton_13 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_13.sizePolicy().hasHeightForWidth())
        self.maxButton_13.setSizePolicy(sizePolicy)
        self.maxButton_13.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_13.setObjectName("maxButton_13")
        self.gridLayout_4.addWidget(self.maxButton_13, 1, 0, 1, 1)
        self.maxButton_12 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_12.sizePolicy().hasHeightForWidth())
        self.maxButton_12.setSizePolicy(sizePolicy)
        self.maxButton_12.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_12.setObjectName("maxButton_12")
        self.gridLayout_4.addWidget(self.maxButton_12, 1, 1, 1, 1)
        self.maxButton_11 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_11.sizePolicy().hasHeightForWidth())
        self.maxButton_11.setSizePolicy(sizePolicy)
        self.maxButton_11.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_11.setObjectName("maxButton_11")
        self.gridLayout_4.addWidget(self.maxButton_11, 1, 2, 1, 1)
        self.maxButton_10 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_10.sizePolicy().hasHeightForWidth())
        self.maxButton_10.setSizePolicy(sizePolicy)
        self.maxButton_10.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_10.setObjectName("pushButton_10")
        self.gridLayout_4.addWidget(self.maxButton_10, 1, 3, 1, 1)
        self.maxButton_23 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_23.sizePolicy().hasHeightForWidth())
        self.maxButton_23.setSizePolicy(sizePolicy)
        self.maxButton_23.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_23.setObjectName("maxButton_23")
        self.gridLayout_4.addWidget(self.maxButton_23, 2, 0, 1, 1)
        self.maxButton_22 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_22.sizePolicy().hasHeightForWidth())
        self.maxButton_22.setSizePolicy(sizePolicy)
        self.maxButton_22.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_22.setObjectName("maxButton_22")
        self.gridLayout_4.addWidget(self.maxButton_22, 2, 1, 1, 1)
        self.maxButton_21 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_21.sizePolicy().hasHeightForWidth())
        self.maxButton_21.setSizePolicy(sizePolicy)
        self.maxButton_21.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_21.setObjectName("maxButton_21")
        self.gridLayout_4.addWidget(self.maxButton_21, 2, 2, 1, 1)
        self.maxButton_20 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_20.sizePolicy().hasHeightForWidth())
        self.maxButton_20.setSizePolicy(sizePolicy)
        self.maxButton_20.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_20.setObjectName("maxButton_20")
        self.gridLayout_4.addWidget(self.maxButton_20, 2, 3, 1, 1)
        self.maxButton_33 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_33.sizePolicy().hasHeightForWidth())
        self.maxButton_33.setSizePolicy(sizePolicy)
        self.maxButton_33.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_33.setObjectName("maxButton_33")
        self.gridLayout_4.addWidget(self.maxButton_33, 3, 0, 1, 1)
        self.maxButton_32 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_32.sizePolicy().hasHeightForWidth())
        self.maxButton_32.setSizePolicy(sizePolicy)
        self.maxButton_32.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_32.setObjectName("maxButton_32")
        self.gridLayout_4.addWidget(self.maxButton_32, 3, 1, 1, 1)
        self.maxButton_31 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_31.sizePolicy().hasHeightForWidth())
        self.maxButton_31.setSizePolicy(sizePolicy)
        self.maxButton_31.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_31.setObjectName("maxButton_31")
        self.gridLayout_4.addWidget(self.maxButton_31, 3, 2, 1, 1)
        self.maxButton_30 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maxButton_30.sizePolicy().hasHeightForWidth())
        self.maxButton_30.setSizePolicy(sizePolicy)
        self.maxButton_30.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.maxButton_30.setObjectName("maxButton_30")
        self.gridLayout_4.addWidget(self.maxButton_30, 3, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(360, 180, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(480, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(540, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(360, 130, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(360, 230, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(360, 280, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(420, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(930, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.layoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_4.setGeometry(QtCore.QRect(730, 110, 238, 211))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget_4.sizePolicy().hasHeightForWidth())
        self.layoutWidget_4.setSizePolicy(sizePolicy)
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.reqButton_03 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_03.sizePolicy().hasHeightForWidth())
        self.reqButton_03.setSizePolicy(sizePolicy)
        self.reqButton_03.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_03.setObjectName("reqButton_03")
        self.gridLayout_5.addWidget(self.reqButton_03, 0, 0, 1, 1)
        self.reqButton_02 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_02.sizePolicy().hasHeightForWidth())
        self.reqButton_02.setSizePolicy(sizePolicy)
        self.reqButton_02.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_02.setObjectName("reqButton_02")
        self.gridLayout_5.addWidget(self.reqButton_02, 0, 1, 1, 1)
        self.reqButton_01 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_01.sizePolicy().hasHeightForWidth())
        self.reqButton_01.setSizePolicy(sizePolicy)
        self.reqButton_01.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_01.setObjectName("reqButton_01")
        self.gridLayout_5.addWidget(self.reqButton_01, 0, 2, 1, 1)
        self.reqButton_00 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_00.sizePolicy().hasHeightForWidth())
        self.reqButton_00.setSizePolicy(sizePolicy)
        self.reqButton_00.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_00.setObjectName("reqButton_00")
        self.gridLayout_5.addWidget(self.reqButton_00, 0, 3, 1, 1)
        self.reqButton_13 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_13.sizePolicy().hasHeightForWidth())
        self.reqButton_13.setSizePolicy(sizePolicy)
        self.reqButton_13.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_13.setObjectName("reqButton_13")
        self.gridLayout_5.addWidget(self.reqButton_13, 1, 0, 1, 1)
        self.reqButton_12 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_12.sizePolicy().hasHeightForWidth())
        self.reqButton_12.setSizePolicy(sizePolicy)
        self.reqButton_12.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_12.setObjectName("reqButton_12")
        self.gridLayout_5.addWidget(self.reqButton_12, 1, 1, 1, 1)
        self.reqButton_11 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_11.sizePolicy().hasHeightForWidth())
        self.reqButton_11.setSizePolicy(sizePolicy)
        self.reqButton_11.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_11.setObjectName("reqButton_11")
        self.gridLayout_5.addWidget(self.reqButton_11, 1, 2, 1, 1)
        self.reqButton_10 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_10.sizePolicy().hasHeightForWidth())
        self.reqButton_10.setSizePolicy(sizePolicy)
        self.reqButton_10.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_10.setObjectName("reqButton_10")
        self.gridLayout_5.addWidget(self.reqButton_10, 1, 3, 1, 1)
        self.reqButton_23 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_23.sizePolicy().hasHeightForWidth())
        self.reqButton_23.setSizePolicy(sizePolicy)
        self.reqButton_23.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_23.setObjectName("reqButton_23")
        self.gridLayout_5.addWidget(self.reqButton_23, 2, 0, 1, 1)
        self.reqButton_22 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_22.sizePolicy().hasHeightForWidth())
        self.reqButton_22.setSizePolicy(sizePolicy)
        self.reqButton_22.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_22.setObjectName("reqButton_22")
        self.gridLayout_5.addWidget(self.reqButton_22, 2, 1, 1, 1)
        self.reqButton_21 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_21.sizePolicy().hasHeightForWidth())
        self.reqButton_21.setSizePolicy(sizePolicy)
        self.reqButton_21.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_21.setObjectName("reqButton_21")
        self.gridLayout_5.addWidget(self.reqButton_21, 2, 2, 1, 1)
        self.reqButton_20 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_20.sizePolicy().hasHeightForWidth())
        self.reqButton_20.setSizePolicy(sizePolicy)
        self.reqButton_20.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_20.setObjectName("reqButton_20")
        self.gridLayout_5.addWidget(self.reqButton_20, 2, 3, 1, 1)
        self.reqButton_33 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_33.sizePolicy().hasHeightForWidth())
        self.reqButton_33.setSizePolicy(sizePolicy)
        self.reqButton_33.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_33.setObjectName("reqButton_33")
        self.gridLayout_5.addWidget(self.reqButton_33, 3, 0, 1, 1)
        self.reqButton_32 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_32.sizePolicy().hasHeightForWidth())
        self.reqButton_32.setSizePolicy(sizePolicy)
        self.reqButton_32.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_32.setObjectName("reqButton_32")
        self.gridLayout_5.addWidget(self.reqButton_32, 3, 1, 1, 1)
        self.reqButton_31 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_31.sizePolicy().hasHeightForWidth())
        self.reqButton_31.setSizePolicy(sizePolicy)
        self.reqButton_31.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_31.setObjectName("reqButton_31")
        self.gridLayout_5.addWidget(self.reqButton_31, 3, 2, 1, 1)
        self.reqButton_30 = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reqButton_30.sizePolicy().hasHeightForWidth())
        self.reqButton_30.setSizePolicy(sizePolicy)
        self.reqButton_30.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.reqButton_30.setObjectName("reqButton_30")
        self.gridLayout_5.addWidget(self.reqButton_30, 3, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(690, 180, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(810, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(870, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(690, 130, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(690, 230, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(690, 280, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(750, 70, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

        self.startButton.clicked.connect(self.start)

        self.allButton_00.clicked.connect(lambda ch, btn=self.allButton_00: self.click_me(btn))
        self.allButton_01.clicked.connect(lambda ch, btn=self.allButton_01: self.click_me(btn))
        self.allButton_02.clicked.connect(lambda ch, btn=self.allButton_02: self.click_me(btn))
        self.allButton_03.clicked.connect(lambda ch, btn=self.allButton_03: self.click_me(btn))
        self.allButton_10.clicked.connect(lambda ch, btn=self.allButton_10: self.click_me(btn))
        self.allButton_11.clicked.connect(lambda ch, btn=self.allButton_11: self.click_me(btn))
        self.allButton_12.clicked.connect(lambda ch, btn=self.allButton_12: self.click_me(btn))
        self.allButton_13.clicked.connect(lambda ch, btn=self.allButton_13: self.click_me(btn))
        self.allButton_20.clicked.connect(lambda ch, btn=self.allButton_20: self.click_me(btn))
        self.allButton_21.clicked.connect(lambda ch, btn=self.allButton_21: self.click_me(btn))
        self.allButton_22.clicked.connect(lambda ch, btn=self.allButton_22: self.click_me(btn))
        self.allButton_23.clicked.connect(lambda ch, btn=self.allButton_23: self.click_me(btn))
        self.allButton_30.clicked.connect(lambda ch, btn=self.allButton_30: self.click_me(btn))
        self.allButton_31.clicked.connect(lambda ch, btn=self.allButton_31: self.click_me(btn))
        self.allButton_32.clicked.connect(lambda ch, btn=self.allButton_32: self.click_me(btn))
        self.allButton_33.clicked.connect(lambda ch, btn=self.allButton_33: self.click_me(btn))

        self.maxButton_00.clicked.connect(lambda ch, btn=self.maxButton_00: self.click_me(btn))
        self.maxButton_01.clicked.connect(lambda ch, btn=self.maxButton_01: self.click_me(btn))
        self.maxButton_02.clicked.connect(lambda ch, btn=self.maxButton_02: self.click_me(btn))
        self.maxButton_03.clicked.connect(lambda ch, btn=self.maxButton_03: self.click_me(btn))
        self.maxButton_10.clicked.connect(lambda ch, btn=self.maxButton_10: self.click_me(btn))
        self.maxButton_11.clicked.connect(lambda ch, btn=self.maxButton_11: self.click_me(btn))
        self.maxButton_12.clicked.connect(lambda ch, btn=self.maxButton_12: self.click_me(btn))
        self.maxButton_13.clicked.connect(lambda ch, btn=self.maxButton_13: self.click_me(btn))
        self.maxButton_20.clicked.connect(lambda ch, btn=self.maxButton_20: self.click_me(btn))
        self.maxButton_21.clicked.connect(lambda ch, btn=self.maxButton_21: self.click_me(btn))
        self.maxButton_22.clicked.connect(lambda ch, btn=self.maxButton_22: self.click_me(btn))
        self.maxButton_23.clicked.connect(lambda ch, btn=self.maxButton_23: self.click_me(btn))
        self.maxButton_30.clicked.connect(lambda ch, btn=self.maxButton_30: self.click_me(btn))
        self.maxButton_31.clicked.connect(lambda ch, btn=self.maxButton_31: self.click_me(btn))
        self.maxButton_32.clicked.connect(lambda ch, btn=self.maxButton_32: self.click_me(btn))
        self.maxButton_33.clicked.connect(lambda ch, btn=self.maxButton_33: self.click_me(btn))

        self.reqButton_00.clicked.connect(lambda ch, btn=self.reqButton_00: self.click_me(btn))
        self.reqButton_01.clicked.connect(lambda ch, btn=self.reqButton_01: self.click_me(btn))
        self.reqButton_02.clicked.connect(lambda ch, btn=self.reqButton_02: self.click_me(btn))
        self.reqButton_03.clicked.connect(lambda ch, btn=self.reqButton_03: self.click_me(btn))
        self.reqButton_10.clicked.connect(lambda ch, btn=self.reqButton_10: self.click_me(btn))
        self.reqButton_11.clicked.connect(lambda ch, btn=self.reqButton_11: self.click_me(btn))
        self.reqButton_12.clicked.connect(lambda ch, btn=self.reqButton_12: self.click_me(btn))
        self.reqButton_13.clicked.connect(lambda ch, btn=self.reqButton_13: self.click_me(btn))
        self.reqButton_20.clicked.connect(lambda ch, btn=self.reqButton_20: self.click_me(btn))
        self.reqButton_21.clicked.connect(lambda ch, btn=self.reqButton_21: self.click_me(btn))
        self.reqButton_22.clicked.connect(lambda ch, btn=self.reqButton_22: self.click_me(btn))
        self.reqButton_23.clicked.connect(lambda ch, btn=self.reqButton_23: self.click_me(btn))
        self.reqButton_30.clicked.connect(lambda ch, btn=self.reqButton_30: self.click_me(btn))
        self.reqButton_31.clicked.connect(lambda ch, btn=self.reqButton_31: self.click_me(btn))
        self.reqButton_32.clicked.connect(lambda ch, btn=self.reqButton_32: self.click_me(btn))
        self.reqButton_33.clicked.connect(lambda ch, btn=self.reqButton_33: self.click_me(btn))

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "BankirAlgorithm"))
        self.label_3.setText(_translate("mainWindow", "Запрос на ресурсы"))
        self.label_28.setText(_translate("mainWindow", "Граф распределения ресурсов"))

        self.startButton.setText(_translate("mainWindow", "START"))
        self.label_6.setText(_translate("mainWindow", "Максимальная потребность"))
        self.label_34.setText(_translate("mainWindow", "R3"))
        self.label_16.setText(_translate("mainWindow", "P4"))
        self.label_35.setText(_translate("mainWindow", "R4"))
        self.label_13.setText(_translate("mainWindow", "P2"))
        self.label_17.setText(_translate("mainWindow", "P3"))
        self.label_36.setText(_translate("mainWindow", "R1"))
        self.label_37.setText(_translate("mainWindow", "R2"))
        self.allButton_03.setText(_translate("mainWindow", "0"))
        self.allButton_02.setText(_translate("mainWindow", "0"))
        self.allButton_01.setText(_translate("mainWindow", "0"))
        self.allButton_00.setText(_translate("mainWindow", "0"))
        self.allButton_13.setText(_translate("mainWindow", "0"))
        self.allButton_12.setText(_translate("mainWindow", "0"))
        self.allButton_11.setText(_translate("mainWindow", "0"))
        self.allButton_10.setText(_translate("mainWindow", "0"))
        self.allButton_23.setText(_translate("mainWindow", "0"))
        self.allButton_22.setText(_translate("mainWindow", "0"))
        self.allButton_21.setText(_translate("mainWindow", "0"))
        self.allButton_20.setText(_translate("mainWindow", "0"))
        self.allButton_33.setText(_translate("mainWindow", "0"))
        self.allButton_32.setText(_translate("mainWindow", "0"))
        self.allButton_31.setText(_translate("mainWindow", "0"))
        self.allButton_30.setText(_translate("mainWindow", "0"))
        self.label_18.setText(_translate("mainWindow", "P1"))
        self.label_4.setText(_translate("mainWindow", "Выделено ресурсов"))
        self.label_38.setText(_translate("mainWindow", "R4"))
        self.maxButton_03.setText(_translate("mainWindow", "0"))
        self.maxButton_02.setText(_translate("mainWindow", "0"))
        self.maxButton_01.setText(_translate("mainWindow", "0"))
        self.maxButton_00.setText(_translate("mainWindow", "0"))
        self.maxButton_13.setText(_translate("mainWindow", "0"))
        self.maxButton_12.setText(_translate("mainWindow", "0"))
        self.maxButton_11.setText(_translate("mainWindow", "0"))
        self.maxButton_10.setText(_translate("mainWindow", "0"))
        self.maxButton_23.setText(_translate("mainWindow", "0"))
        self.maxButton_22.setText(_translate("mainWindow", "0"))
        self.maxButton_21.setText(_translate("mainWindow", "0"))
        self.maxButton_20.setText(_translate("mainWindow", "0"))
        self.maxButton_33.setText(_translate("mainWindow", "0"))
        self.maxButton_32.setText(_translate("mainWindow", "0"))
        self.maxButton_31.setText(_translate("mainWindow", "0"))
        self.maxButton_30.setText(_translate("mainWindow", "0"))
        self.label_14.setText(_translate("mainWindow", "P2"))
        self.label_39.setText(_translate("mainWindow", "R2"))
        self.label_40.setText(_translate("mainWindow", "R3"))
        self.label_19.setText(_translate("mainWindow", "P1"))
        self.label_20.setText(_translate("mainWindow", "P3"))
        self.label_21.setText(_translate("mainWindow", "P4"))
        self.label_41.setText(_translate("mainWindow", "R1"))
        self.label_42.setText(_translate("mainWindow", "R4"))
        self.reqButton_03.setText(_translate("mainWindow", "0"))
        self.reqButton_02.setText(_translate("mainWindow", "0"))
        self.reqButton_01.setText(_translate("mainWindow", "0"))
        self.reqButton_00.setText(_translate("mainWindow", "0"))
        self.reqButton_13.setText(_translate("mainWindow", "0"))
        self.reqButton_12.setText(_translate("mainWindow", "0"))
        self.reqButton_11.setText(_translate("mainWindow", "0"))
        self.reqButton_10.setText(_translate("mainWindow", "0"))
        self.reqButton_23.setText(_translate("mainWindow", "0"))
        self.reqButton_22.setText(_translate("mainWindow", "0"))
        self.reqButton_21.setText(_translate("mainWindow", "0"))
        self.reqButton_20.setText(_translate("mainWindow", "0"))
        self.reqButton_33.setText(_translate("mainWindow", "0"))
        self.reqButton_32.setText(_translate("mainWindow", "0"))
        self.reqButton_31.setText(_translate("mainWindow", "0"))
        self.reqButton_30.setText(_translate("mainWindow", "0"))
        self.label_15.setText(_translate("mainWindow", "P2"))
        self.label_43.setText(_translate("mainWindow", "R2"))
        self.label_44.setText(_translate("mainWindow", "R3"))
        self.label_22.setText(_translate("mainWindow", "P1"))
        self.label_23.setText(_translate("mainWindow", "P3"))
        self.label_24.setText(_translate("mainWindow", "P4"))
        self.label_45.setText(_translate("mainWindow", "R1"))

    def click_me(self, btn):
        if btn.text() == '0':
            btn.setText('1')
            btn.setStyleSheet("background-color: gray; color: white;")
        else:
            btn.setText('0')
            btn.setStyleSheet("background-color: lightgray;")

    def read_buttons(self) -> tuple[list[list[int]], list[list[int]], list[list[int]]]:
        def to_int(matrix: list[list[str]]) -> list[list[int]]:
            return list(map(lambda l: list(map(int, l)), matrix))

        currently_allocated = [
            [self.allButton_00.text(), self.allButton_01.text(), self.allButton_02.text(), self.allButton_03.text()],
            [self.allButton_10.text(), self.allButton_11.text(), self.allButton_12.text(), self.allButton_13.text()],
            [self.allButton_20.text(), self.allButton_21.text(), self.allButton_22.text(), self.allButton_23.text()],
            [self.allButton_30.text(), self.allButton_31.text(), self.allButton_32.text(), self.allButton_33.text()],
        ]

        max_need = [
            [self.maxButton_00.text(), self.maxButton_01.text(), self.maxButton_02.text(), self.maxButton_03.text()],
            [self.maxButton_10.text(), self.maxButton_11.text(), self.maxButton_12.text(), self.maxButton_13.text()],
            [self.maxButton_20.text(), self.maxButton_21.text(), self.maxButton_22.text(), self.maxButton_23.text()],
            [self.maxButton_30.text(), self.maxButton_31.text(), self.maxButton_32.text(), self.maxButton_33.text()],
        ]

        currently_request = [
            [self.reqButton_00.text(), self.reqButton_01.text(), self.reqButton_02.text(), self.reqButton_03.text()],
            [self.reqButton_10.text(), self.reqButton_11.text(), self.reqButton_12.text(), self.reqButton_13.text()],
            [self.reqButton_20.text(), self.reqButton_21.text(), self.reqButton_22.text(), self.reqButton_23.text()],
            [self.reqButton_30.text(), self.reqButton_31.text(), self.reqButton_32.text(), self.reqButton_33.text()],
        ]

        return to_int(currently_allocated), to_int(max_need), to_int(currently_request)

    def start(self):
        currently_allocated, max_need, currently_request = self.read_buttons()
        allocated = [0] * resources
        for i in range(processes):
            for j in range(resources):
                allocated[j] += currently_allocated[i][j]
        available = [max_resources[i] - allocated[i] for i in range(resources)]

        lst, lab, seq, draw1, draw2, rest = bankir(processes, resources, max_resources, max_need, currently_allocated,
                                                   currently_request, available, allocated, sequence, label)
        drawer = GraphDrawer.GraphDrawer(config)
        self.label_29.setText(lab)
        self.label_30.setText(seq)

        def update_str():
            lst_all = [
                [self.allButton_00, self.allButton_01, self.allButton_02, self.allButton_03],
                [self.allButton_10, self.allButton_11, self.allButton_12, self.allButton_13],
                [self.allButton_20, self.allButton_21, self.allButton_22, self.allButton_23],
                [self.allButton_30, self.allButton_31, self.allButton_32, self.allButton_33]
            ]
            lst_req = [
                [self.reqButton_00, self.reqButton_01, self.reqButton_02, self.reqButton_03],
                [self.reqButton_10, self.reqButton_11, self.reqButton_12, self.reqButton_13],
                [self.reqButton_20, self.reqButton_21, self.reqButton_22, self.reqButton_23],
                [self.reqButton_30, self.reqButton_31, self.reqButton_32, self.reqButton_33]
            ]

            self.svgWidget.show()
            for x, line in enumerate(lst):
                for but in range(4):
                    lst_all[line][but].setText('0')
                    lst_all[line][but].setStyleSheet("background-color: green; color: white;")
                    lst_req[line][but].setText('0')
                    lst_req[line][but].setStyleSheet("background-color: green; color: white;")
                    
                    dwg = drawer.draw(draw1[x], draw2[x])
                    dwg.saveas(f"Pictures/example{x}.svg")
                    self.svgWidget.load(f"Pictures/example{x}.svg")
                    
                    loop = QEventLoop()
                    QTimer.singleShot(1000, loop.quit)
                    loop.exec()
        update_str()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
